export enum ordersStatusList {
  ORDERED = 'ORDERED', // 1
  INITIATED = 'INITIATED', // 2
  COMPLETED = 'COMPLETED', // 3
  DELIVERED = 'DELIVERED', // 4
  CANCELLED = 'CANCELLED', // 5
  REFUNDED = 'REFUNDED', // 6
}
